export enum TransactionType {
  CAPTURE = 'CAPTURE',
  PRE_AUTH = 'PRE_AUTH',
  PURCHASED = 'PURCHASED',
  VOID = 'VOID',
  REFUND = 'REFUND',
  DECLINED = 'DECLINED',
  PENDING = 'PENDING',
  EXPIRED = 'EXPIRED',
  CANCELLED = 'CANCELLED',
}
